version: '3.4'

# Services
services:

# PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: 127.0.0.1
      PMA_PORT: 3306
      APACHE_PORT: 7000
    network_mode: host

  # Touchon
  touchon:
    env_file:
      - ./.env
    build:
      context: ./src/
      args:
        UBUNTU_VERSION: jammy
      dockerfile: Dockerfile.dev
    container_name: touchon
    restart: always
    volumes:
      - workdir:/opt/touchon/workdir
      - ~/touchon/src/configs:/opt/touchon/configs
      - ~/touchon/src/scripts:/opt/touchon/scripts
      - ~/touchon/apps/adm:/opt/touchon/workdir/adm
      - ~/touchon/apps/server:/opt/touchon/workdir/server
      - ~/.hostpipe:/opt/touchon/hostpipe
      - ~/.dockerpipe:/opt/touchon/dockerpipe
      - /etc/network/interfaces.d/netcfg:/etc/network/interfaces.d/netcfg
      - ~/.ssh:/root/.ssh
    network_mode: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"

  # MediaMTX
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: always
    environment:
      MTX_API: yes
      MTX_APIADDRESS: :9997
      MTX_RTMP: no
      MTX_RTSP: no
      MTX_WEBRTC: no
      MTX_SRT: no
      MTX_PROTOCOLS: tcp
      MTX_HLSENCRYPTION: false
    # volumes:
    #   - ./mediamtx/server.key:/server.key
    #   - ./mediamtx/server.crt:/server.crt
    network_mode: host

volumes:
  workdir:
