version: '3.4'

# Services
services:

# PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: 127.0.0.1
      PMA_PORT: 3306
      APACHE_PORT: 7000
    network_mode: host

  # Touchon
  touchon:
    env_file:
      - ./.env
    build:
      context: ./src/
      dockerfile: Dockerfile
    container_name: touchon
    restart: always
    volumes:
      - workdir:/opt/touchon/workdir
      - /home/touchon/.hostpipe:/opt/touchon/hostpipe
      - /home/touchon/.dockerpipe:/opt/touchon/dockerpipe
      - /etc/network/interfaces.d/netcfg:/etc/network/interfaces.d/netcfg
    network_mode: host

# Volumes
volumes:
  workdir: