ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION}

ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=en_GB.UTF-8
ENV LANGUAGE=en_GB.UTF-8
ENV LC_ALL=en_GB.UTF-8
WORKDIR /opt/touchon

RUN apt-get update \ 
    && apt-get install -y --no-install-recommends --no-install-suggests locales locales-all \
    && apt-get install -y --no-install-recommends --no-install-suggests supervisor nginx tzdata mariadb-server \
    mariadb-client iputils-ping cron php-fpm php-bcmath php-mbstring php-mysqli php-pdo php-xml php-curl rsync \
    openssh-client tar sshpass lftp wget unzip nano gettext-base composer git ca-certificates \
    && phpVersion=$(php -v | head -n 1 | awk '/PHP/ {print $2}' | cut -d. -f1,2) \
    && sed -i 's,;clear_env = no,clear_env = no,g' /etc/php/${phpVersion}/fpm/pool.d/www.conf \
    && sed -i 's,user =.*,user = root,' /etc/php/${phpVersion}/fpm/pool.d/www.conf \
    && sed -i 's,group =.*,group = root,' /etc/php/${phpVersion}/fpm/pool.d/www.conf \
    && crontab -l | { cat; echo '*/1 * * * * cd ${WORK_DIR}/server && php cron.php 1'; } | crontab - \
    && crontab -l | { cat; echo '*/5 * * * * cd ${WORK_DIR}/server && php cron.php 5'; } | crontab - \
    && crontab -l | { cat; echo '*/10 * * * * cd ${WORK_DIR}/server && php cron.php 10'; } | crontab - \
    && crontab -l | { cat; echo '*/15 * * * * cd ${WORK_DIR}/server && php cron.php 15'; } | crontab - \
    && crontab -l | { cat; echo '*/30 * * * * cd ${WORK_DIR}/server && php cron.php 30'; } | crontab - \
    && crontab -l | { cat; echo '*/60 * * * * cd ${WORK_DIR}/server && php cron.php 60'; } | crontab - \
    && crontab -l | { cat; echo '*/1 * * * * cd ${WORK_DIR}/server && php main.php'; } | crontab - \
    && crontab -l | { cat; echo '00 01 * * * cd /opt/touchon/scripts && ./backup.sh'; } | crontab - \
    && crontab -l | { cat; echo '*/1 * * * * cd ${WORK_DIR}/server && php watchdog.php'; } | crontab - \
    && mkdir -p /var/log/supervisor \
    && mkdir -p /run/mysqld \
    && chown -R mysql:mysql /run/mysqld \
    && ln -s /opt/touchon/scripts/rs_control/rs_control /usr/bin/rs_control

CMD ["/usr/bin/supervisord", "-c", "/opt/touchon/configs/supervisord.conf"]